#!/bin/sh

# cleanup 

rm -rf obj_dir
rm -f sinegen.vcd
rm -f counter.vcd
rm -f rom.vcd

# run Verilator to translate Verligo into C++, including C++ testbench 
verilator -Wall --cc --trace sinegen.sv --exe sinegen_tb.cpp
verilator -Wall --cc --trace counter.sv --exe sinegen_tb.cpp
verilator -Wall --cc --trace rom.sv --exe sinegen_tb.cpp

# build C++ project via make automatically generated by Verilator 
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen

# run executable simulation file 
obj_dir/Vsinegen